import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s), base=n=>n.replace(/\.[^.]+$/,''), esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>{if(n<1024)return n+' B';let v=n/1024,i=0;while(v>=1024&&i<2){v/=1024;i++}return v.toFixed(v>=100?0:v>=10?1:2)+' '+['KB','MB','GB'][i]};
const A={tool:null,files:[],busy:false,cancel:false,order:[]};
const E={home:$('#home-view'),tool:$('#tool-view'),title:$('#tool-title'),label:$('#tool-step-label'),drop:$('#drop-zone'),input:$('#file-input'),button:$('#file-button'),hint:$('#file-hint'),settings:$('#settings-panel'),files:$('#files-panel'),progress:$('#progress-panel'),result:$('#result-panel'),error:$('#error-panel')};
const META={
 'pdf-rotate':['PDFを回転','ページの向きを90°単位で変更','回転したいPDFを選択してください','全ページまたは指定ページ'],
 'pdf-nup':['2・4ページ → 1枚','複数ページを1枚にまとめて印刷','PDFを選択してください','2ページまたは4ページを1枚に'],
 'pdf-organize':['PDF整理','ページの削除・抽出・並べ替え','整理したいPDFを選択してください','ページを選んで並べ替え'],
 'pdf-compress':['PDFを軽量化','PDFの容量を小さくする','軽量化したいPDFを選択してください','画質と容量のバランスを選択']};
function dl(b,n){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function err(m,t=''){E.error.hidden=false;E.error.innerHTML='<strong>'+esc(m)+'</strong>'+(t?'<div class="hint">'+esc(t)+'</div>':'')}
function clear(){E.error.hidden=true;E.error.textContent=''}
function step(n){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n))}
function prog(d,t,s){E.progress.hidden=false;E.progress.innerHTML=`<div class="progress-text"><strong>${esc(s)}</strong><span>${d} / ${t}</span></div><div class="progress-bar"><div class="progress-fill" style="width:${t?Math.round(d/t*100):0}%"></div></div><div class="actions"><button class="secondary-button" id="adv-cancel">キャンセル</button></div>`;$('#adv-cancel').onclick=()=>A.cancel=true}
async function pdf(f){try{return await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise}catch(e){if(e?.name==='PasswordException')throw Error('password');throw Error('pdf')}}
function pageNums(s,max){if(!s.trim())return[];const out=[];for(const x of s.split(',')){const m=x.trim().match(/^(\d+)(?:\s*[-~〜]\s*(\d+))?$/);if(!m)continue;let a=+m[1],b=m[2]?+m[2]:a;if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.push(n)}return[...new Set(out)]}
function home(){A.files=[];A.order=[];E.tool.hidden=true;E.home.hidden=false;[E.settings,E.files,E.progress,E.result].forEach(x=>{x.hidden=true;x.innerHTML=''});clear()}
function open(t){A.tool=t;A.files=[];A.order=[];A.cancel=false;E.home.hidden=true;E.tool.hidden=false;E.title.textContent=META[t][0];E.label.textContent='① ファイルを入れる';E.hint.textContent=META[t][2];E.input.accept='application/pdf';E.input.multiple=false;[E.settings,E.files,E.progress,E.result].forEach(x=>{x.hidden=true;x.innerHTML='' });clear();step(1)}
function showSettings(){E.settings.hidden=false;step(2);let h='';if(A.tool==='pdf-rotate')h='<h3>回転設定</h3><div class="settings-grid"><div class="field"><label>回転角度</label><select id="ar"><option value="90">90° 時計回り</option><option value="180">180°</option><option value="270">270° 時計回り</option></select></div><div class="field"><label>対象ページ</label><select id="arp"><option value="all">全ページ</option><option value="range">指定ページ</option></select></div><div class="field" id="arw" hidden><label>ページ範囲</label><input id="arr" placeholder="例：1-3,5,8"></div></div><div class="actions"><button class="primary-button" id="astart">PDFを回転</button></div>';
else if(A.tool==='pdf-nup')h='<h3>印刷設定</h3><div class="settings-grid"><div class="field"><label>まとめるページ数</label><select id="an"><option value="2">2ページ → 1枚</option><option value="4">4ページ → 1枚</option></select></div><div class="field"><label>並べ方</label><select id="al"><option value="vertical">縦に並べる</option><option value="horizontal">横に並べる</option></select></div><div class="field"><label>用紙</label><select id="as"><option value="p">A4 縦</option><option value="l">A4 横</option></select></div></div><div class="actions"><button class="primary-button" id="astart">PDFを作成</button></div>';
else if(A.tool==='pdf-organize')h='<h3>整理設定</h3><p class="field-note">ページの順番を確認して、不要なページを削除します。抽出にも使えます。</p><div class="actions"><button class="primary-button" id="astart">整理したPDFを作成</button></div>';
else h='<h3>軽量化設定</h3><div class="settings-grid"><div class="field"><label>軽量化レベル</label><select id="ac"><option value="high">画質優先</option><option value="std" selected>標準</option><option value="light">容量優先</option></select><span class="field-note">PDFを画像として再構成します。文字の選択・検索などが失われる場合があります。</span></div></div><div class="actions"><button class="primary-button" id="astart">軽量化する</button></div>';
E.settings.innerHTML=h;$('#astart').onclick=run;const p=$('#arp');if(p)p.onchange=()=>$('#arw').hidden=p.value!=='range'}
function listFiles(){E.files.hidden=false;E.files.innerHTML=`<h3>選択したPDF</h3><div class="file-list"><div class="file-row"><div><div class="file-name">${esc(A.files[0].name)}</div><div class="file-meta">${fmt(A.files[0].size)}</div></div></div></div>`;showSettings();if(A.tool==='pdf-organize')loadOrder()}
async function loadOrder(){const p=await pdf(A.files[0]);A.order=Array.from({length:p.numPages},(_,i)=>i+1);renderOrder()}
function renderOrder(){E.files.hidden=false;E.files.innerHTML=`<h3>ページ ${A.order.length}枚</h3><div class="file-list" id="order-list"></div>`;const box=$('#order-list');A.order.forEach((n,i)=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<div><div class="file-name">${i+1}. ページ ${n}</div></div><div class="thumb-controls"><button data-a="up" ${i?'':'disabled'}>↑</button><button data-a="down" ${i===A.order.length-1?'disabled':''}>↓</button><button data-a="del" ${A.order.length<=1?'disabled':''}>削除</button></div>`;row.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='del')A.order.splice(i,1);if(a==='up'&&i)[A.order[i-1],A.order[i]]=[A.order[i],A.order[i-1]];if(a==='down'&&i<A.order.length-1)[A.order[i+1],A.order[i]]=[A.order[i],A.order[i+1]];renderOrder()});box.appendChild(row)});showSettings()}
async function run(){if(A.busy||!A.files.length)return;A.busy=true;A.cancel=false;clear();try{step(3);let r;if(A.tool==='pdf-rotate')r=await rotate();else if(A.tool==='pdf-nup')r=await nup();else if(A.tool==='pdf-organize')r=await organize();else r=await compress();if(!A.cancel)result(r)}catch(e){console.error(e);if(e.message==='password')err('このPDFはパスワードで保護されているため読み込めませんでした。','パスワードを解除したPDFで試してください。');else err('PDFを処理できませんでした。','ファイルを小さくする、ページ数を減らす、または別のブラウザで試してください。')}finally{A.busy=false}}
async function rotate(){const {PDFDocument,degrees}=PDFLib,d=await PDFDocument.load(await A.files[0].arrayBuffer()),n=d.getPageCount(),targets=$('#arp').value==='all'?Array.from({length:n},(_,i)=>i+1):pageNums($('#arr').value,n);if(!targets.length)throw Error('range');const a=+$('#ar').value;targets.forEach(i=>{const p=d.getPage(i-1);p.setRotation(degrees((p.getRotation().angle+a)%360))});prog(1,1,'回転完了');return[{blob:new Blob([await d.save()],{type:'application/pdf'}),name:base(A.files[0].name)+'_回転.pdf'}]}
async function nup(){const src=await pdf(A.files[0]),count=+$('#an').value,land=$('#as').value==='l',pw=land?842:595,ph=land?595:842,layout=$('#al').value,d=await PDFLib.PDFDocument.create(),groups=Math.ceil(src.numPages/count);for(let g=0;g<groups;g++){if(A.cancel)break;prog(g,groups,`${g+1} / ${groups} 枚を作成中`);const page=d.addPage([pw,ph]),cw=layout==='horizontal'?pw/count:pw,ch=layout==='horizontal'?ph:ph/count;for(let j=0;j<count&&g*count+j<src.numPages;j++){const p=await src.getPage(g*count+j+1),v=p.getViewport({scale:1}),sc=Math.min((cw-18)/v.width,(ch-18)/v.height),c=document.createElement('canvas');c.width=Math.ceil(v.width*sc);c.height=Math.ceil(v.height*sc);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:p.getViewport({scale:sc}),background:'white'}).promise;const b=await new Promise((r,x)=>c.toBlob(z=>z?r(z):x(Error('encode')),'image/jpeg',.84)),jpg=await d.embedJpg(new Uint8Array(await b.arrayBuffer()));const x=layout==='horizontal'?j*cw+(cw-c.width)/2:(cw-c.width)/2,y=layout==='horizontal'?(ph-c.height)/2:ph-(j+1)*ch+(ch-c.height)/2;page.drawImage(jpg,{x,y,width:c.width,height:c.height});c.width=c.height=1;await new Promise(r=>setTimeout(r,0))}}prog(groups,groups,'PDF作成完了');return[{blob:new Blob([await d.save()],{type:'application/pdf'}),name:base(A.files[0].name)+`_${count}ページまとめ.pdf`}]}
async function organize(){const d=await PDFLib.PDFDocument.load(await A.files[0].arrayBuffer()),out=await PDFLib.PDFDocument.create();if(!A.order.length)throw Error('range');const pages=await out.copyPages(d,A.order.map(x=>x-1));pages.forEach(p=>out.addPage(p));prog(1,1,'整理完了');return[{blob:new Blob([await out.save()],{type:'application/pdf'}),name:base(A.files[0].name)+'_整理済み.pdf'}]}
async function compress(){const src=await pdf(A.files[0]),level=$('#ac').value,cfg=level==='high'?{s:.9,q:.82}:level==='light'?{s:.65,q:.55}:{s:.75,q:.68},d=await PDFLib.PDFDocument.create();for(let i=0;i<src.numPages;i++){if(A.cancel)break;prog(i,src.numPages,`${i+1} / ${src.numPages}ページを軽量化中`);const p=await src.getPage(i+1),v=p.getViewport({scale:cfg.s}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,background:'white'}).promise;const b=await new Promise((r,x)=>c.toBlob(z=>z?r(z):x(Error('encode')),'image/jpeg',cfg.q)),jpg=await d.embedJpg(new Uint8Array(await b.arrayBuffer()));const pg=d.addPage([v.width,v.height]);pg.drawImage(jpg,{x:0,y:0,width:v.width,height:v.height});c.width=c.height=1;await new Promise(r=>setTimeout(r,0))}const blob=new Blob([await d.save()],{type:'application/pdf'});if(blob.size>=A.files[0].size)return[{blob:A.files[0],name:base(A.files[0].name)+'_そのまま.pdf',original:A.files[0].size,note:'元のPDFのほうが小さいため、元ファイルを保存します。'}];return[{blob,name:base(A.files[0].name)+'_軽量版.pdf',original:A.files[0].size}]}
function result(rs){step(4);E.result.hidden=false;const orig=rs.reduce((a,x)=>a+(x.original||0),0),after=rs.reduce((a,x)=>a+x.blob.size,0);E.result.innerHTML=`<h3>変換しました！</h3>${orig?`<div class="result-summary"><div><span>元サイズ</span><strong>${fmt(orig)}</strong></div><div><span>変換後</span><strong>${fmt(after)}</strong></div><div><span>削減率</span><strong>${Math.max(0,Math.round((1-after/orig)*100))}%</strong></div></div>`:''}<div class="result-list">${rs.map((x,i)=>`<div class="file-row"><div><div class="file-name">${esc(x.name)}</div><div class="file-meta">${fmt(x.blob.size)}${x.note?' · '+esc(x.note):''}</div></div><button class="primary-button" data-d="${i}">ダウンロード</button></div>`).join('')}</div><div class="actions"><button class="secondary-button" id="aagain">もう一度</button></div>`;E.result.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>dl(rs[+b.dataset.d].blob,rs[+b.dataset.d].name));$('#aagain').onclick=()=>open(A.tool)}
function add(fs){if(!fs.length)return;A.files=[fs[0]];listFiles()}
function makeCards(){const grid=$('.tool-grid');if(!grid)return;[['pdf-rotate','PDF↻','PDFを回転','ページの向きを変更'],['pdf-nup','2→1','2・4ページ → 1枚','印刷しやすくまとめる'],['pdf-organize','PDF☷','PDF整理','削除・抽出・並べ替え'],['pdf-compress','PDF↓','PDFを軽量化','PDFの容量を小さくする']].forEach(([id,icon,title,sub])=>{if(grid.querySelector(`[data-tool="${id}"]`))return;const b=document.createElement('button');b.className='tool-card';b.type='button';b.dataset.tool=id;b.innerHTML=`<span class="tool-icon pdf" aria-hidden="true">${icon}</span><span><strong>${title}</strong><small>${sub}</small></span><span class="arrow" aria-hidden="true">›</span>`;b.onclick=()=>open(id);grid.appendChild(b)})}
function init(){makeCards();E.button.onclick=()=>E.input.click();E.drop.onclick=e=>{if(e.target!==E.button)E.input.click()};E.drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();E.input.click()}};E.input.onchange=e=>{add([...e.target.files]);e.target.value=''};['dragenter','dragover'].forEach(v=>E.drop.addEventListener(v,e=>{e.preventDefault();E.drop.classList.add('dragover')}));['dragleave','drop'].forEach(v=>E.drop.addEventListener(v,e=>{e.preventDefault();E.drop.classList.remove('dragover')}));E.drop.addEventListener('drop',e=>{e.preventDefault();add([...e.dataTransfer.files])});document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
