import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),base=s=>s.replace(/\.[^.]+$/,'');
const q=new URLSearchParams(location.search),tool=q.get('tool')||'rotate';const names={rotate:['PDFを回転','ページの向きを90°単位で変更','回転したいPDFを選択してください'],nup:['2・4ページ → 1枚','複数ページを1枚にまとめて印刷','PDFを選択してください'],organize:['PDF整理','ページの削除・抽出・並べ替え','整理したいPDFを選択してください'],compress:['PDFを軽量化','PDFの容量を小さくする','軽量化したいPDFを選択してください']};
const E={title:$('#title'),hint:$('#hint'),drop:$('#drop'),pick:$('#pick'),input:$('#input'),files:$('#files'),settings:$('#settings'),progress:$('#progress'),result:$('#result'),error:$('#error')};let file=null,order=[],cancel=false;
const fmt=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
function step(n){document.querySelectorAll('.step').forEach((x,i)=>x.classList.toggle('active',i===n-1))}function clear(){[E.files,E.settings,E.progress,E.result].forEach(x=>{x.hidden=true;x.innerHTML='' });E.error.hidden=true;E.error.textContent=''}function error(m,t=''){E.error.hidden=false;E.error.innerHTML='<strong>'+esc(m)+'</strong>'+(t?'<div class="hint">'+esc(t)+'</div>':'')}function prog(d,t,s){E.progress.hidden=false;E.progress.innerHTML=`<div class="progress-text"><strong>${esc(s)}</strong><span>${d} / ${t}</span></div><div class="progress-bar"><div class="progress-fill" style="width:${t?d/t*100:0}%"></div></div><div class="actions"><button class="secondary-button" id="cancel">キャンセル</button></div>`;$('#cancel').onclick=()=>cancel=true}
async function load(f){try{return await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise}catch(e){if(e?.name==='PasswordException')throw Error('password');throw e}}
function range(s,max){const out=[];for(const z of s.split(',')){const m=z.trim().match(/^(\d+)(?:\s*[-~〜]\s*(\d+))?$/);if(!m)continue;let a=+m[1],b=m[2]?+m[2]:a;if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++)if(i>=1&&i<=max)out.push(i)}return[...new Set(out)]}
function setFile(f){if(!f)return;if(f.type!=='application/pdf'&&!f.name.toLowerCase().endsWith('.pdf'))return error('PDFファイルを選択してください。');file=f;E.files.hidden=false;E.files.innerHTML=`<h3>選択したPDF</h3><div class="file-list"><div class="file-row"><div><div class="file-name">${esc(f.name)}</div><div class="file-meta">${fmt(f.size)}</div></div></div></div>`;if(tool==='organize')loadOrder();else settings()}
async function loadOrder(){try{const p=await load(file);order=Array.from({length:p.numPages},(_,i)=>i+1);renderOrder()}catch(e){error(e.message==='password'?'このPDFはパスワードで保護されています。':'このPDFは読み込めませんでした。')}}
function renderOrder(){E.files.innerHTML=`<h3>ページ ${order.length}枚</h3><div class="file-list" id="ol"></div>`;const box=$('#ol');order.forEach((n,i)=>{const r=document.createElement('div');r.className='file-row';r.innerHTML=`<div><div class="file-name">${i+1}. ページ ${n}</div></div><div class="thumb-controls"><button data-a="u" ${i?'':'disabled'}>↑</button><button data-a="d" ${i===order.length-1?'disabled':''}>↓</button><button data-a="x" ${order.length<=1?'disabled':''}>削除</button></div>`;r.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='x')order.splice(i,1);if(a==='u'&&i)[order[i-1],order[i]]=[order[i],order[i-1]];if(a==='d'&&i<order.length-1)[order[i+1],order[i]]=[order[i],order[i+1]];renderOrder()});box.appendChild(r)});settings()}
function settings(){E.settings.hidden=false;step(2);let h;if(tool==='rotate')h='<h3>回転設定</h3><div class="settings-grid"><div class="field"><label>回転角度</label><select id="ang"><option value="90">90° 時計回り</option><option value="180">180°</option><option value="270">270° 時計回り</option></select></div><div class="field"><label>対象ページ</label><select id="tar"><option value="all">全ページ</option><option value="range">指定ページ</option></select></div><div class="field" id="rw" hidden><label>ページ範囲</label><input id="rng" placeholder="例：1-3,5,8"></div></div>';
else if(tool==='nup')h='<h3>印刷設定</h3><div class="settings-grid"><div class="field"><label>まとめるページ数</label><select id="num"><option value="2">2ページ → 1枚</option><option value="4">4ページ → 1枚</option></select></div><div class="field"><label>並べ方</label><select id="lay"><option value="vertical">縦に並べる</option><option value="horizontal">横に並べる</option></select></div><div class="field"><label>用紙</label><select id="paper"><option value="p">A4 縦</option><option value="l">A4 横</option></select></div></div>';
else if(tool==='organize')h='<h3>整理設定</h3><p class="field-note">ページを削除・並べ替えできます。残したページだけで新しいPDFを作ります。</p>';
else h='<h3>軽量化設定</h3><div class="settings-grid"><div class="field"><label>軽量化レベル</label><select id="level"><option value="high">画質優先</option><option value="std" selected>標準</option><option value="light">容量優先</option></select><span class="field-note">PDFを画像として再構成します。文字の選択・検索などが失われる場合があります。</span></div></div>';
E.settings.innerHTML=h+`<div class="actions"><button class="primary-button" id="start">${tool==='rotate'?'PDFを回転':tool==='organize'?'整理したPDFを作成':tool==='compress'?'軽量化する':'PDFを作成'}</button></div>`;$('#start').onclick=run;const tar=$('#tar');if(tar)tar.onchange=()=>$('#rw').hidden=tar.value!=='range'}
async function run(){cancel=false;clear();step(3);try{let r;if(tool==='rotate')r=await rotate();else if(tool==='nup')r=await nup();else if(tool==='organize')r=await organize();else r=await compress();if(!cancel)show(r)}catch(e){console.error(e);error(e.message==='password'?'このPDFはパスワードで保護されています。':'PDFを処理できませんでした。','ファイルを小さくする、ページ数を減らす、または別のブラウザで試してください。')}}
async function rotate(){const d=await PDFLib.PDFDocument.load(await file.arrayBuffer()),n=d.getPageCount(),t=$('#tar').value==='all'?Array.from({length:n},(_,i)=>i+1):range($('#rng').value,n);if(!t.length)throw Error('range');const a=+$('#ang').value;t.forEach(i=>{const p=d.getPage(i-1);p.setRotation(PDFLib.degrees((p.getRotation().angle+a)%360))});prog(1,1,'回転完了');return[{blob:new Blob([await d.save()],{type:'application/pdf'}),name:base(file.name)+'_回転.pdf'}]}
async function nup(){const src=await load(file),count=+$('#num').value,land=$('#paper').value==='l',pw=land?842:595,ph=land?595:842,lay=$('#lay').value,d=await PDFLib.PDFDocument.create(),groups=Math.ceil(src.numPages/count);for(let g=0;g<groups;g++){if(cancel)break;prog(g,groups,`${g+1} / ${groups} 枚を作成中`);const pg=d.addPage([pw,ph]),cw=lay==='horizontal'?pw/count:pw,ch=lay==='horizontal'?ph:ph/count;for(let j=0;j<count&&g*count+j<src.numPages;j++){const p=await src.getPage(g*count+j+1),v=p.getViewport({scale:1}),sc=Math.min((cw-16)/v.width,(ch-16)/v.height),c=document.createElement('canvas');c.width=Math.ceil(v.width*sc);c.height=Math.ceil(v.height*sc);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:p.getViewport({scale:sc}),background:'white'}).promise;const b=await new Promise((r,x)=>c.toBlob(z=>z?r(z):x(Error('encode')),'image/jpeg',.84)),jpg=await d.embedJpg(new Uint8Array(await b.arrayBuffer()));const x=lay==='horizontal'?j*cw+(cw-c.width)/2:(cw-c.width)/2,y=lay==='horizontal'?(ph-c.height)/2:ph-(j+1)*ch+(ch-c.height)/2;pg.drawImage(jpg,{x,y,width:c.width,height:c.height});c.width=c.height=1}}return[{blob:new Blob([await d.save()],{type:'application/pdf'}),name:base(file.name)+`_${count}ページまとめ.pdf`}]}
async function organize(){const d=await PDFLib.PDFDocument.load(await file.arrayBuffer()),o=await PDFLib.PDFDocument.create(),p=await o.copyPages(d,order.map(x=>x-1));p.forEach(x=>o.addPage(x));return[{blob:new Blob([await o.save()],{type:'application/pdf'}),name:base(file.name)+'_整理済み.pdf'}]}
async function compress(){const src=await load(file),lv=$('#level').value,c=lv==='high'?{s:.9,q:.82}:lv==='light'?{s:.65,q:.55}:{s:.75,q:.68},d=await PDFLib.PDFDocument.create();for(let i=0;i<src.numPages;i++){if(cancel)break;prog(i,src.numPages,`${i+1} / ${src.numPages}ページを軽量化中`);const p=await src.getPage(i+1),v=p.getViewport({scale:c.s}),cv=document.createElement('canvas');cv.width=Math.ceil(v.width);cv.height=Math.ceil(v.height);await p.render({canvasContext:cv.getContext('2d',{alpha:false}),viewport:v,background:'white'}).promise;const b=await new Promise((r,x)=>cv.toBlob(z=>z?r(z):x(Error('encode')),'image/jpeg',c.q)),jpg=await d.embedJpg(new Uint8Array(await b.arrayBuffer()));const pg=d.addPage([v.width,v.height]);pg.drawImage(jpg,{x:0,y:0,width:v.width,height:v.height});cv.width=cv.height=1}const blob=new Blob([await d.save()],{type:'application/pdf'});return blob.size<file.size?[{blob,name:base(file.name)+'_軽量版.pdf',original:file.size}]:[{blob:file,name:base(file.name)+'_そのまま.pdf',original:file.size,note:'元のPDFのほうが小さいため、元ファイルを保存します。'}]}
function show(rs){step(4);E.result.hidden=false;E.result.innerHTML='<h3>変換しました！</h3>'+rs.map((r,i)=>`<div class="file-row"><div><div class="file-name">${esc(r.name)}</div><div class="file-meta">${fmt(r.blob.size)}${r.original?' · 元 '+fmt(r.original):''}${r.note?' · '+esc(r.note):''}</div></div><button class="primary-button" data-i="${i}">ダウンロード</button></div>`).join('')+'<div class="actions"><a class="secondary-button" href="index.html">トップへ戻る</a></div>';E.result.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const r=rs[+b.dataset.i],u=URL.createObjectURL(r.blob),a=document.createElement('a');a.href=u;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)})}
E.title.textContent=names[tool]?.[0]||'PDFツール';E.hint.textContent=names[tool]?.[2]||'';E.pick.onclick=()=>E.input.click();E.drop.onclick=e=>{if(e.target!==E.pick)E.input.click()};E.input.onchange=e=>{setFile(e.target.files[0]);e.target.value=''};E.drop.ondragover=e=>{e.preventDefault();E.drop.classList.add('dragover')};E.drop.ondragleave=()=>E.drop.classList.remove('dragover');E.drop.ondrop=e=>{e.preventDefault();E.drop.classList.remove('dragover');setFile(e.dataTransfer.files[0])};E.drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();E.input.click()}};
