import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s);const S={tool:null,files:[],results:[],busy:false,cancelled:false};
const E={home:$('#home-view'),tool:$('#tool-view'),title:$('#tool-title'),label:$('#tool-step-label'),drop:$('#drop-zone'),input:$('#file-input'),button:$('#file-button'),hint:$('#file-hint'),settings:$('#settings-panel'),files:$('#files-panel'),progress:$('#progress-panel'),result:$('#result-panel'),error:$('#error-panel')};
const fmt=n=>{if(!Number.isFinite(n))return'-';if(n<1024)return`${n} B`;const u=['KB','MB','GB'];let i=-1,v=n;do{v/=1024;i++}while(v>=1024&&i<u.length-1);return`${v.toFixed(v>=100?0:v>=10?1:2)} ${u[i]}`};const base=n=>n.replace(/\.[^.]+$/,'');const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const tick=()=>new Promise(r=>setTimeout(r,0));
function dl(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function err(msg,tip=''){E.error.hidden=false;E.error.innerHTML=`<strong>${esc(msg)}</strong>${tip?`<div class="hint">${esc(tip)}</div>`:''}`}function clearErr(){E.error.hidden=true;E.error.textContent=''}function step(n){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===n))}
function progress(done,total,text){E.progress.hidden=false;E.progress.innerHTML=`<div class="progress-text"><strong>${esc(text)}</strong><span>${done} / ${total}</span></div><div class="progress-bar"><div class="progress-fill" style="width:${total?Math.round(done/total*100):0}%"></div></div><div class="actions"><button class="secondary-button" id="cancel" type="button">キャンセル</button></div>`;$('#cancel').onclick=()=>S.cancelled=true}
function reset(){[E.settings,E.files,E.progress,E.result].forEach(x=>{x.hidden=true;x.innerHTML='' });clearErr()}
const META={
'pdf-image':['PDF → 画像','PDFをPNG・JPG・WebPに変換','PDFを選択してください','application/pdf',false],
'image-webp':['画像 → WebP','画像を軽くしてWeb用に','JPG・PNGなどの画像を選択してください','image/*',true],
'image-pdf':['画像 → PDF','複数の画像を1つのPDFにまとめる','PDFにしたい画像を選択してください','image/*',true],
'pdf-merge':['PDFを結合','複数のPDFを1つにまとめる','結合したいPDFを選択してください','application/pdf',true],
'pdf-split':['PDFを分割','PDFをページごと・範囲ごとに分ける','分割したいPDFを選択してください','application/pdf',false]};
function openTool(t){S.tool=t;S.files=[];S.results=[];S.cancelled=false;reset();E.home.hidden=true;E.tool.hidden=false;E.title.textContent=META[t][0];E.label.textContent='① ファイルを入れる';E.hint.textContent=META[t][2];E.input.accept=META[t][3];E.input.multiple=META[t][4];step(1)}
function home(){S.busy=false;S.files=[];reset();E.tool.hidden=true;E.home.hidden=false}
function image(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=()=>{URL.revokeObjectURL(u);rej(new Error('image'))};im.src=u})}
function ranges(text,max){if(!text.trim())return Array.from({length:max},(_,i)=>i+1);const out=new Set();for(const raw of text.split(',')){const p=raw.trim();if(/^\d+$/.test(p)){const n=+p;if(n>=1&&n<=max)out.add(n)}else{const m=p.match(/^(\d+)\s*[-~〜]\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.add(n)}}}return[...out].sort((a,b)=>a-b)}
function settings(){E.settings.hidden=false;step(2);let h='';if(S.tool==='pdf-image')h=`<h3>変換設定</h3><div class="settings-grid"><div class="field"><label for="type">画像形式</label><select id="type"><option value="image/png">PNG</option><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option></select></div><div class="field"><label for="scale">画像サイズ</label><select id="scale"><option value="1">標準</option><option value="1.5">高解像度</option><option value="0.75">軽量</option></select></div><div class="field"><label for="prange">ページ範囲</label><input id="prange" placeholder="全ページ（例：1-5）"><span class="field-note">空欄なら全ページ。例：1-5、3,5,8</span></div><div class="field"><label for="quality">画質</label><div class="range-line"><input id="quality" type="range" min="30" max="100" value="85"><span class="value-chip" id="qv">85%</span></div></div></div><div class="actions"><button class="primary-button" id="start">変換を開始</button></div>`;
else if(S.tool==='image-webp')h=`<h3>軽量化設定</h3><div class="settings-grid"><div class="field"><label for="preset">品質</label><select id="preset"><option value="0.9">高画質</option><option value="0.78" selected>標準</option><option value="0.6">軽量</option><option value="custom">詳細設定</option></select></div><div class="field"><label for="max">長辺サイズ</label><select id="max"><option value="0">元サイズを維持</option><option value="2400">2400 px</option><option value="1600">1600 px</option><option value="1200">1200 px</option><option value="800">800 px</option></select></div><div class="field" id="custom" hidden><label for="wq">詳細画質</label><div class="range-line"><input id="wq" type="range" min="30" max="100" value="78"><span class="value-chip" id="wqv">78%</span></div></div></div><div class="actions"><button class="primary-button" id="start">変換を開始</button></div>`;
else if(S.tool==='image-pdf')h=`<h3>PDF設定</h3><div class="settings-grid"><div class="field"><label for="pdfsize">用紙サイズ</label><select id="pdfsize"><option value="a4p">A4 縦</option><option value="a4l">A4 横</option><option value="fit">画像に合わせる</option></select></div></div><div class="actions"><button class="primary-button" id="start">PDFを作成</button></div>`;
else if(S.tool==='pdf-merge')h=`<h3>結合設定</h3><p class="field-note">下の一覧で順番を確認してから結合します。</p><div class="actions"><button class="primary-button" id="start">PDFを結合</button></div>`;
else h=`<h3>分割設定</h3><div class="settings-grid"><div class="field"><label for="smode">分割方法</label><select id="smode"><option value="pages">1ページずつ分割</option><option value="range">指定した範囲ごとに分割</option></select></div><div class="field" id="srf" hidden><label for="srange">ページ範囲</label><input id="srange" placeholder="例：1-3,4-6,7-10"><span class="field-note">各範囲が1つのPDFになります。</span></div></div><div class="actions"><button class="primary-button" id="start">PDFを分割</button></div>`;E.settings.innerHTML=h;$('#start').onclick=process;const q=$('#quality');if(q)q.oninput=()=>$('#qv').textContent=q.value+'%';const wq=$('#wq');if(wq)wq.oninput=()=>$('#wqv').textContent=wq.value+'%';const p=$('#preset');if(p)p.onchange=()=>$('#custom').hidden=p.value!=='custom';const sm=$('#smode');if(sm)sm.onchange=()=>$('#srf').hidden=sm.value!=='range'}
function list(){E.files.hidden=false;if(S.tool==='image-pdf'){E.files.innerHTML=`<h3>画像 ${S.files.length}枚</h3><div class="thumb-list" id="thumbs"></div>`;thumbs()}else{E.files.innerHTML=`<h3>選択したファイル ${S.files.length}</h3><div class="file-list">${S.files.map((f,i)=>`<div class="file-row"><div><div class="file-name">${i+1}. ${esc(f.name)}</div><div class="file-meta">${fmt(f.size)}</div></div>${S.tool==='pdf-merge'?`<button class="secondary-button" data-r="${i}">削除</button>`:''}</div>`).join('')}</div>`;E.files.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{S.files.splice(+b.dataset.r,1);list()})}settings()}
function thumbs(){const box=$('#thumbs');S.files.forEach((f,i)=>{const c=document.createElement('div');c.className='thumb-card';c.draggable=true;c.innerHTML=`<img alt="" src="${URL.createObjectURL(f)}"><div class="thumb-body"><div class="thumb-name">${esc(f.name)}</div><div class="thumb-controls"><button data-a="up" ${i?'':'disabled'}>↑</button><button data-a="down" ${i===S.files.length-1?'disabled':''}>↓</button><button data-a="delete">削除</button></div></div>`;c.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='delete')S.files.splice(i,1);if(a==='up'&&i)[S.files[i-1],S.files[i]]=[S.files[i],S.files[i-1]];if(a==='down'&&i<S.files.length-1)[S.files[i+1],S.files[i]]=[S.files[i],S.files[i+1]];list()});c.ondragover=e=>e.preventDefault();c.ondragstart=e=>e.dataTransfer.setData('text/plain',i);c.ondrop=e=>{e.preventDefault();const from=+e.dataTransfer.getData('text/plain');if(from!==i){const[x]=S.files.splice(from,1);S.files.splice(i,0,x);list()}};box.appendChild(c)})}
async function loadPdf(f){try{return await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise}catch(e){if(e?.name==='PasswordException')throw new Error('password');throw new Error('pdf')}}
async function pdfImages(){const pdf=await loadPdf(S.files[0]),ps=ranges($('#prange').value,pdf.numPages),type=$('#type').value,scale=+$('#scale').value,q=+$('#quality').value/100,out=[];if(!ps.length)throw new Error('range');for(let i=0;i<ps.length;i++){if(S.cancelled)break;const n=ps[i];progress(i,ps.length,`${n}ページを処理中`);const p=await pdf.getPage(n),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,background:'white'}).promise;const b=await new Promise((r,j)=>c.toBlob(x=>x?r(x):j(new Error('encode')),type,q));out.push({blob:b,name:`${base(S.files[0].name)}_${String(n).padStart(3,'0')}.${type==='image/png'?'png':type==='image/jpeg'?'jpg':'webp'}`});c.width=c.height=1;await tick()}progress(ps.length,ps.length,'変換完了');return out}
async function webp(){const p=$('#preset').value,q=p==='custom'?+$('#wq').value/100:+p,max=+$('#max').value,out=[];for(let i=0;i<S.files.length;i++){if(S.cancelled)break;const f=S.files[i];progress(i,S.files.length,`${i+1} / ${S.files.length}枚を処理中`);const im=await image(f);let w=im.naturalWidth,h=im.naturalHeight;if(max&&Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);const b=await new Promise((r,j)=>c.toBlob(x=>x?r(x):j(new Error('encode')),'image/webp',q));out.push({blob:b,name:`${base(f.name)}.webp`,original:f.size});c.width=c.height=1;await tick()}progress(S.files.length,S.files.length,'変換完了');return out}
async function imagePdf(){const {PDFDocument}=window.PDFLib||{};if(!PDFDocument)throw new Error('pdf-lib');const d=await PDFDocument.create(),sz=$('#pdfsize').value;for(let i=0;i<S.files.length;i++){if(S.cancelled)break;progress(i,S.files.length,`${i+1} / ${S.files.length}枚をPDFに追加中`);const f=S.files[i],im=await image(f),iw=im.naturalWidth,ih=im.naturalHeight;let pw,ph;if(sz==='a4p'){pw=595.28;ph=841.89}else if(sz==='a4l'){pw=841.89;ph=595.28}else{pw=iw*72/96;ph=ih*72/96}const page=d.addPage([pw,ph]),c=document.createElement('canvas');c.width=iw;c.height=ih;c.getContext('2d').drawImage(im,0,0);const b=await new Promise((r,j)=>c.toBlob(x=>x?r(x):j(new Error('encode')),'image/jpeg',.92)),jpg=await d.embedJpg(new Uint8Array(await b.arrayBuffer()));const s=Math.min(pw/iw,ph/ih),dw=iw*s,dh=ih*s;page.drawImage(jpg,{x:(pw-dw)/2,y:(ph-dh)/2,width:dw,height:dh});c.width=c.height=1;await tick()}progress(S.files.length,S.files.length,'PDF作成完了');return[{blob:new Blob([await d.save()],{type:'application/pdf'}),name:`${base(S.files[0].name)}.pdf`}]}
async function merge(){const {PDFDocument}=window.PDFLib||{};if(!PDFDocument)throw new Error('pdf-lib');const out=await PDFDocument.create();for(let i=0;i<S.files.length;i++){if(S.cancelled)break;progress(i,S.files.length,`${i+1} / ${S.files.length} 個目のPDFを追加中`);const src=await PDFDocument.load(await S.files[i].arrayBuffer());(await out.copyPages(src,src.getPageIndices())).forEach(p=>out.addPage(p));await tick()}progress(S.files.length,S.files.length,'結合完了');return[{blob:new Blob([await out.save()],{type:'application/pdf'}),name:'結合したPDF.pdf'}]}
async function split(){const {PDFDocument}=window.PDFLib||{};if(!PDFDocument)throw new Error('pdf-lib');const src=await PDFDocument.load(await S.files[0].arrayBuffer()),n=src.getPageCount();let groups;if($('#smode').value==='pages')groups=Array.from({length:n},(_,i)=>[i]);else{const rs=ranges($('#srange').value,n);if(!rs.length)throw new Error('range');groups=[rs.map(x=>x-1)]}const out=[];for(let i=0;i<groups.length;i++){if(S.cancelled)break;progress(i,groups.length,`${i+1} / ${groups.length} 個のPDFを作成中`);const d=await PDFDocument.create();(await d.copyPages(src,groups[i])).forEach(p=>d.addPage(p));out.push({blob:new Blob([await d.save()],{type:'application/pdf'}),name:`${base(S.files[0].name)}_${String(i+1).padStart(3,'0')}.pdf`});await tick()}progress(groups.length,groups.length,'分割完了');return out}
async function process(){if(S.busy||!S.files.length)return;S.busy=true;S.cancelled=false;clearErr();try{step(3);S.results=S.tool==='pdf-image'?await pdfImages():S.tool==='image-webp'?await webp():S.tool==='image-pdf'?await imagePdf():S.tool==='pdf-merge'?await merge():await split();if(!S.cancelled)result();else E.progress.innerHTML='<strong>処理をキャンセルしました。</strong>'}catch(e){console.error(e);const m=String(e.message||e);err(m==='password'?'このPDFはパスワードで保護されているため読み込めませんでした。':m==='range'?'ページ範囲を確認してください。存在するページ番号を入力してください。':m==='image'?'画像を読み込めませんでした。対応形式かどうか確認してください。':m==='pdf-lib'?'PDF処理ライブラリを読み込めませんでした。':'PDF・画像を処理できませんでした。','ファイルを小さくする、ページ数を減らす、または別のブラウザで試してください。')}finally{S.busy=false}}
async function result(){step(4);E.result.hidden=false;const total=S.results.reduce((a,r)=>a+r.blob.size,0);let stat=`<span class="stat">${S.results.length}ファイル</span><span class="stat">合計 ${fmt(total)}</span>`;if(S.tool==='image-webp'){const before=S.results.reduce((a,r)=>a+r.original,0),rate=before?Math.max(0,Math.round((1-total/before)*100)):0;stat+=`<span class="stat">元サイズ ${fmt(before)}</span><span class="stat">${rate}%軽量化</span>`}E.result.innerHTML=`<div class="result-title">✓ 変換しました！</div><div class="result-summary">${stat}</div><div class="file-list">${S.results.map((r,i)=>`<div class="file-row"><div><div class="file-name">${esc(r.name)}</div><div class="file-meta">${fmt(r.blob.size)}</div></div><button class="secondary-button" data-dl="${i}">ダウンロード</button></div>`).join('')}</div><div class="actions"><button class="primary-button" id="zip">まとめてZIP</button><button class="secondary-button" id="again">もう一度変換</button></div>`;S.results.forEach((r,i)=>E.result.querySelector(`[data-dl="${i}"]`).onclick=()=>dl(r.blob,r.name));$('#zip').onclick=async()=>{const z=new JSZip;S.results.forEach(r=>z.file(r.name,r.blob));dl(await z.generateAsync({type:'blob'}),'ファイル工房_変換結果.zip')};$('#again').onclick=()=>{reset();list()}}
function accept(files){const a=[...files];if(!a.length)return;S.files=(S.tool==='pdf-image'||S.tool==='pdf-split')?[a[0]]:a;list()}
E.button.onclick=e=>{e.stopPropagation();E.input.click()};E.input.onchange=()=>{accept(E.input.files);E.input.value=''};E.drop.onclick=e=>{if(!e.target.closest('button'))E.input.click()};E.drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();E.input.click()}};['dragenter','dragover'].forEach(x=>E.drop.addEventListener(x,e=>{e.preventDefault();E.drop.classList.add('dragover')}));['dragleave','drop'].forEach(x=>E.drop.addEventListener(x,e=>{e.preventDefault();E.drop.classList.remove('dragover')}));E.drop.addEventListener('drop',e=>accept(e.dataTransfer.files));document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool));document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);
