import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';

pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';

const $ = (s) => document.querySelector(s);
const state = { tool:null, files:[], results:[], busy:false, cancelled:false };
const els = { home:$('#home-view'), tool:$('#tool-view'), title:$('#tool-title'), label:$('#tool-step-label'), drop:$('#drop-zone'), input:$('#file-input'), fileButton:$('#file-button'), hint:$('#file-hint'), settings:$('#settings-panel'), files:$('#files-panel'), progress:$('#progress-panel'), result:$('#result-panel'), error:$('#error-panel') };
const sleep = () => new Promise(r => setTimeout(r, 0));
const fmt = (n) => { if (!Number.isFinite(n)) return '-'; if(n<1024) return `${n} B`; const u=['KB','MB','GB']; let i=-1,v=n; do{v/=1024;i++;}while(v>=1024&&i<u.length-1); return `${v.toFixed(v>=100?0:v>=10?1:2)} ${u[i]}`; };
const ext = (name) => (name.split('.').pop()||'').toLowerCase();
const baseName = (name) => name.replace(/\.[^.]+$/,'');
const escapeHtml = (s) => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function downloadBlob(blob,name){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function blobFromCanvas(canvas,type,quality){ return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('encode')),type,quality)); }
function showError(message,tip=''){ els.error.hidden=false; els.error.innerHTML=`<strong>${escapeHtml(message)}</strong>${tip?`<div class="hint">${escapeHtml(tip)}</div>`:''}`; }
function clearError(){els.error.hidden=true;els.error.textContent='';}
function setProgress(done,total,text){ els.progress.hidden=false; const pct=total?Math.round(done/total*100):0; els.progress.innerHTML=`<div class="progress-text"><strong>${escapeHtml(text)}</strong><span>${done} / ${total}</span></div><div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div><div class="actions"><button class="secondary-button" id="cancel-btn" type="button">キャンセル</button></div>`; $('#cancel-btn').onclick=()=>{state.cancelled=true;}; }
function setStep(n){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));}
function resetPanels(){[els.settings,els.files,els.progress,els.result].forEach(x=>{x.hidden=true;x.innerHTML='';});clearError();}
function openTool(tool){ state.tool=tool;state.files=[];state.results=[];state.cancelled=false;resetPanels();els.home.classList.remove('active');els.home.hidden=true;els.tool.hidden=false;els.tool.classList.add('active');
  const meta={ 'pdf-image':['PDF → 画像','PDFをPNG・JPG・WebPに変換','PDFを選択してください','application/pdf'], 'image-webp':['画像 → WebP','画像を軽くしてWeb用に','JPG・PNGなどの画像を選択してください','image/*'], 'image-pdf':['画像 → PDF','複数の画像を1つのPDFにまとめる','PDFにしたい画像を選択してください','image/*'] }[tool];
  els.title.textContent=meta[0];els.label.textContent='① ファイルを入れる';els.hint.textContent=meta[2];els.input.accept=meta[3];els.input.multiple=tool!=='pdf-image';setStep(1);
}
function home(){state.busy=false;state.files=[];resetPanels();els.tool.hidden=true;els.tool.classList.remove('active');els.home.hidden=false;els.home.classList.add('active');}
async function readImage(file){ return new Promise((resolve,reject)=>{ const url=URL.createObjectURL(file); const img=new Image(); img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url; }); }
function parseRange(text,max){ if(!text.trim()) return Array.from({length:max},(_,i)=>i+1); const out=new Set(); for(const part of text.split(',')){const p=part.trim(); if(/^\d+$/.test(p)){const n=Number(p);if(n>=1&&n<=max)out.add(n);continue;} const m=p.match(/^(\d+)\s*[-~〜]\s*(\d+)$/);if(m){let a=Number(m[1]),b=Number(m[2]);if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.add(n);}} return [...out].sort((a,b)=>a-b); }
function renderSettings(){ els.settings.hidden=false; setStep(2);
 if(state.tool==='pdf-image') els.settings.innerHTML=`<h3>変換設定</h3><div class="settings-grid"><div class="field"><label for="out-type">画像形式</label><select id="out-type"><option value="image/png">PNG</option><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option></select></div><div class="field"><label for="scale">画像サイズ</label><select id="scale"><option value="1">標準</option><option value="1.5">高解像度</option><option value="0.75">軽量</option></select><span class="field-note">高解像度ほどファイルが大きくなります。</span></div><div class="field"><label for="pdf-range">ページ範囲</label><input id="pdf-range" inputmode="text" placeholder="全ページ（例：1-5）"><span class="field-note">全ページなら空欄。例：1-5、3,5,8</span></div><div class="field" id="quality-wrap"><label for="quality">画質</label><div class="range-line"><input id="quality" type="range" min="30" max="100" value="85"><span class="value-chip" id="quality-value">85%</span></div></div></div><div class="actions"><button class="primary-button" id="start-btn" type="button">変換を開始</button></div>`;
 else if(state.tool==='image-webp') els.settings.innerHTML=`<h3>軽量化設定</h3><div class="settings-grid"><div class="field"><label for="webp-preset">品質</label><select id="webp-preset"><option value="0.9">高画質</option><option value="0.78" selected>標準</option><option value="0.6">軽量</option><option value="custom">詳細設定</option></select></div><div class="field"><label for="max-side">長辺サイズ</label><select id="max-side"><option value="0" selected>元サイズを維持</option><option value="2400">2400 px</option><option value="1600">1600 px</option><option value="1200">1200 px</option><option value="800">800 px</option></select></div><div class="field" id="custom-quality" hidden><label for="webp-quality">詳細画質</label><div class="range-line"><input id="webp-quality" type="range" min="30" max="100" value="78"><span class="value-chip" id="webp-quality-value">78%</span></div></div></div><div class="actions"><button class="primary-button" id="start-btn" type="button">変換を開始</button></div>`;
 else els.settings.innerHTML=`<h3>PDF設定</h3><div class="settings-grid"><div class="field"><label for="pdf-size">用紙サイズ</label><select id="pdf-size"><option value="a4p">A4 縦</option><option value="a4l">A4 横</option><option value="fit">画像に合わせる</option></select></div><div class="field"><label>画像の順番</label><span class="field-note">下のサムネイルで ↑ ↓ を使って変更できます。</span></div></div><div class="actions"><button class="primary-button" id="start-btn" type="button">PDFを作成</button></div>`;
 $('#start-btn').onclick=()=>process(); const q=$('#quality');if(q)q.oninput=()=>$('#quality-value').textContent=q.value+'%'; const wq=$('#webp-quality');if(wq)wq.oninput=()=>$('#webp-quality-value').textContent=wq.value+'%'; const preset=$('#webp-preset');if(preset)preset.onchange=()=>$('#custom-quality').hidden=preset.value!=='custom';
}
function renderFileList(){ els.files.hidden=false; if(state.tool==='image-pdf'){ els.files.innerHTML=`<h3>画像 ${state.files.length}枚</h3><div class="thumb-list" id="thumb-list"></div>`; renderThumbs(); }
 else {els.files.innerHTML=`<h3>選択したファイル</h3><div class="file-list">${state.files.map(f=>`<div class="file-row"><div><div class="file-name">${escapeHtml(f.name)}</div><div class="file-meta">${fmt(f.size)}</div></div></div>`).join('')}</div>`;}
 renderSettings(); }
function renderThumbs(){ const list=$('#thumb-list');list.innerHTML='';state.files.forEach((f,i)=>{const card=document.createElement('div');card.className='thumb-card';card.draggable=true;card.dataset.i=i;card.innerHTML=`<img alt="" src="${URL.createObjectURL(f)}"><div class="thumb-body"><div class="thumb-name" title="${escapeHtml(f.name)}">${escapeHtml(f.name)}</div><div class="thumb-controls"><button type="button" data-act="up" ${i===0?'disabled':''}>↑</button><button type="button" data-act="down" ${i===state.files.length-1?'disabled':''}>↓</button><button type="button" data-act="delete">削除</button></div></div>`;card.querySelectorAll('button').forEach(b=>b.onclick=()=>{const act=b.dataset.act;if(act==='delete')state.files.splice(i,1);if(act==='up'&&i>0)[state.files[i-1],state.files[i]]=[state.files[i],state.files[i-1]];if(act==='down'&&i<state.files.length-1)[state.files[i+1],state.files[i]]=[state.files[i],state.files[i+1]];renderFileList();});card.ondragstart=()=>card.classList.add('sortable-drag');card.ondragend=()=>card.classList.remove('sortable-drag');card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));const to=i;if(Number.isInteger(from)&&from!==to){const [x]=state.files.splice(from,1);state.files.splice(to,0,x);renderFileList();}};card.ondragstart=e=>{card.classList.add('sortable-drag');e.dataTransfer.setData('text/plain',String(i));};list.appendChild(card);});}
async function process(){ if(state.busy||!state.files.length)return;state.busy=true;state.cancelled=false;clearError();els.settings.querySelectorAll('button').forEach(b=>b.disabled=true);try{setStep(3);state.results=state.tool==='pdf-image'?await pdfToImages():state.tool==='image-webp'?await imagesToWebp():await imagesToPdf();if(!state.cancelled)showResult();else{els.progress.innerHTML='<strong>変換をキャンセルしました。</strong><div class="actions"><button class="secondary-button" id="retry-btn">もう一度</button></div>';$('#retry-btn').onclick=()=>{els.progress.hidden=true;state.busy=false;};}}catch(e){console.error(e);showError(userError(e), 'ファイルを小さくする、ページ数を減らす、または別のブラウザで試してください。');}finally{state.busy=false;els.settings.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function userError(e){const m=String(e?.message||e);if(m.includes('password'))return 'このPDFはパスワードで保護されているため読み込めませんでした。';if(m.includes('memory')||m.includes('Array buffer'))return 'メモリ不足の可能性があります。ページ数や画像サイズを減らして試してください。';if(m==='image')return '画像を読み込めませんでした。対応形式かどうか確認してください。';return state.tool==='pdf-image'?'このPDFは読み込めませんでした。':'変換中に問題が発生しました。';}
async function pdfToImages(){const file=state.files[0];const data=await file.arrayBuffer();let pdf;try{pdf=await pdfjsLib.getDocument({data}).promise;}catch(e){throw new Error(e?.name==='PasswordException'?'password':'pdf');}const pages=parseRange($('#pdf-range').value,pdf.numPages);if(!pages.length)throw new Error('range');const type=$('#out-type').value,scale=Number($('#scale').value),quality=Number($('#quality').value)/100,out=[];for(let j=0;j<pages.length;j++){if(state.cancelled)break;const n=pages[j];setProgress(j,pages.length,`${n}ページを処理中`);const page=await pdf.getPage(n);const vp=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);const ctx=canvas.getContext('2d',{alpha:false});await page.render({canvasContext:ctx,viewport:vp,background:'white'}).promise;const blob=await blobFromCanvas(canvas,type,quality);const suffix=type==='image/png'?'png':type==='image/jpeg'?'jpg':'webp';out.push({blob,name:`${baseName(file.name)}_${String(n).padStart(3,'0')}.${suffix}`});canvas.width=1;canvas.height=1;await sleep();}setProgress(pages.length,pages.length,'変換完了');return out;}
async function imagesToWebp(){const preset=$('#webp-preset').value;const quality=preset==='custom'?Number($('#webp-quality').value)/100:Number(preset);const max=Number($('#max-side').value);const out=[];for(let i=0;i<state.files.length;i++){if(state.cancelled)break;const f=state.files[i];setProgress(i,state.files.length,`${i+1} / ${state.files.length}枚を処理中`);const img=await readImage(f);let w=img.naturalWidth,h=img.naturalHeight;if(max&&Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r);}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);const blob=await blobFromCanvas(c,'image/webp',quality);out.push({blob,name:`${baseName(f.name)}.webp`,original:f.size});c.width=1;c.height=1;await sleep();}setProgress(state.files.length,state.files.length,'変換完了');return out;}
async function imagesToPdf(){const {PDFDocument}=window.PDFLib||{};if(!PDFDocument)throw new Error('pdf-lib');const doc=await PDFDocument.create();const size=$('#pdf-size').value;for(let i=0;i<state.files.length;i++){if(state.cancelled)break;setProgress(i,state.files.length,`${i+1} / ${state.files.length}枚をPDFに追加中`);const f=state.files[i];const img=await readImage(f);const iw=img.naturalWidth,ih=img.naturalHeight;let pw,ph;if(size==='a4p'){pw=595.28;ph=841.89;}else if(size==='a4l'){pw=841.89;ph=595.28;}else{pw=iw*72/96;ph=ih*72/96;}const page=doc.addPage([pw,ph]);const c=document.createElement('canvas');c.width=iw;c.height=ih;c.getContext('2d').drawImage(img,0,0);let embedded;if(ext(f.name)==='png')embedded=await doc.embedPng(await c.toDataURL('image/png'));else{const jpg=await blobFromCanvas(c,'image/jpeg',.92);embedded=await doc.embedJpg(await jpg.arrayBuffer());}const scale=Math.min(pw/iw,ph/ih);const dw=iw*scale,dh=ih*scale;page.drawImage(embedded,{x:(pw-dw)/2,y:(ph-dh)/2,width:dw,height:dh});c.width=1;c.height=1;await sleep();}setProgress(state.files.length,state.files.length,'PDFを作成しました');const bytes=await doc.save();return [{blob:new Blob([bytes],{type:'application/pdf'}),name:'ファイル工房_まとめ.pdf'}];}
function showResult(){setStep(4);els.result.hidden=false;const total=state.results.reduce((s,r)=>s+r.blob.size,0);const original=state.tool==='image-webp'?state.files.reduce((s,f)=>s+f.size,0):null;let stats=state.tool==='image-webp'&&original?`<span class="stat">変換前 ${fmt(original)}</span><span class="stat">変換後 ${fmt(total)}</span><span class="stat">${Math.max(0,Math.round((1-total/original)*100))}%軽量化</span>`:`<span class="stat">${state.results.length}ファイル</span><span class="stat">合計 ${fmt(total)}</span>`;els.result.innerHTML=`<div class="result-title">✓ 変換しました！</div><div class="result-summary">${stats}</div><div class="file-list">${state.results.map((r,i)=>`<div class="file-row"><div><div class="file-name">${escapeHtml(r.name)}</div><div class="file-meta">${fmt(r.blob.size)}</div></div><button class="secondary-button" data-download="${i}" type="button">ダウンロード</button></div>`).join('')}</div><div class="actions"><button class="primary-button" id="zip-btn" type="button">まとめてZIP</button><button class="secondary-button" id="again-btn" type="button">もう一度変換</button></div>`;els.result.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>{const r=state.results[Number(b.dataset.download)];downloadBlob(r.blob,r.name)});$('#zip-btn').onclick=zipAll;$('#again-btn').onclick=()=>{state.files=[];state.results=[];resetPanels();els.drop.hidden=false;setStep(1);};}
async function zipAll(){if(!window.JSZip)return showError('ZIP機能を読み込めませんでした。','ページを再読み込みして、もう一度お試しください。');const zip=new JSZip();state.results.forEach(r=>zip.file(r.name,r.blob));const blob=await zip.generateAsync({type:'blob'});downloadBlob(blob,`ファイル工房_${new Date().toISOString().slice(0,10)}.zip`);}
function acceptFiles(files){const arr=[...files];if(!arr.length)return;if(state.tool==='pdf-image'&&arr.length>1)arr.splice(1);const valid=arr.filter(f=>state.tool==='pdf-image'?f.type==='application/pdf'||ext(f.name)==='pdf':/^image\/(jpeg|png|webp|gif|bmp|avif)$/i.test(f.type)||/\.(jpe?g|png|webp|gif|bmp|avif)$/i.test(f.name));if(!valid.length)return showError('対応しているファイルを選択してください。');state.files=state.tool==='pdf-image'?valid.slice(0,1):valid;els.drop.hidden=true;clearError();renderFileList();}
els.fileButton.onclick=e=>{e.stopPropagation();els.input.click();};els.input.onchange=e=>acceptFiles(e.target.files);els.drop.onclick=e=>{if(e.target===els.fileButton)return;els.input.click();};els.drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.input.click();}};['dragenter','dragover'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.add('dragover');}));['dragleave','drop'].forEach(ev=>els.drop.addEventListener(ev,e=>{e.preventDefault();els.drop.classList.remove('dragover');}));els.drop.ondrop=e=>acceptFiles(e.dataTransfer.files);document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool));document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);