import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s);const file=$('#file'),drop=$('#drop'),panel=$('#file-panel'),settings=$('#settings'),progress=$('#progress'),result=$('#result'),error=$('#error');let selected=null;
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const base=s=>s.replace(/\.[^.]+$/,'');
function dl(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function showError(m){error.hidden=false;error.innerHTML=`<strong>${esc(m)}</strong>`}
function ranges(text,max){if(!text.trim())return Array.from({length:max},(_,i)=>i+1);const out=new Set();for(const x of text.split(',')){const p=x.trim();if(/^\d+$/.test(p)){const n=+p;if(n>=1&&n<=max)out.add(n)}else{const m=p.match(/^(\d+)\s*[-~〜]\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.add(n)}}}return [...out].sort((a,b)=>a-b)}
function prog(done,total,msg){progress.hidden=false;progress.innerHTML=`<div class="progress-text"><strong>${esc(msg)}</strong><span>${done}/${total}</span></div><div class="progress-bar"><div class="progress-fill" style="width:${Math.round(done/total*100)}%"></div></div>`}
function choose(f){if(!f||f.type!=='application/pdf'){showError('PDFファイルを選択してください。');return}selected=f;error.hidden=true;panel.hidden=false;panel.innerHTML=`<h3>選択したPDF</h3><div class="file-row"><div><div class="file-name">${esc(f.name)}</div><div class="file-meta">${(f.size/1024/1024).toFixed(2)} MB</div></div><span>✓</span></div>`;settings.hidden=false;result.hidden=true}
$('#pick').onclick=()=>file.click();file.onchange=()=>choose(file.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');choose(e.dataTransfer.files[0])};drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')file.click()};
$('#run').onclick=async()=>{if(!selected)return;result.hidden=true;error.hidden=true;try{const pdf=await pdfjsLib.getDocument({data:await selected.arrayBuffer()}).promise;const mode=$('#mode').value,scale=+$('#scale').value,pages=ranges($('#range').value,pdf.numPages);if(!pages.length)throw new Error('ページ範囲が正しくありません。');let textParts=[],images=[];for(let i=0;i<pages.length;i++){const n=pages[i];prog(i,pages.length,`${n}ページを処理中`);const p=await pdf.getPage(n);if(mode!=='image'){const tc=await p.getTextContent();let lines=[],lastY=null;for(const item of tc.items){if(lastY!==null&&Math.abs(item.transform[5]-lastY)>4)lines.push('\n');lines.push(item.str);lastY=item.transform[5]}textParts.push(`===== ${n}ページ =====\n${lines.join('')}\n`)}if(mode!=='text'){const v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,background:'white'}).promise;const blob=await new Promise((r,j)=>c.toBlob(x=>x?r(x):j(new Error('画像生成に失敗しました')),'image/png'));images.push({blob,name:`${base(selected.name)}_${String(n).padStart(3,'0')}.png`});c.width=c.height=1}prog(i+1,pages.length,`${n}ページ完了`)}let buttons='';if(mode!=='text'){if(images.length===1)buttons+=`<button class="primary-button" id="download-image">画像を保存</button>`;else buttons+=`<button class="primary-button" id="download-images">画像をZIPで保存</button>`}if(mode!=='image')buttons+=`<button class="secondary-button" id="download-text">テキストを保存</button>`;result.hidden=false;result.innerHTML=`<div class="result-title">✓ 抽出が完了しました</div><div class="result-summary"><span class="stat">${pages.length}ページ</span>${mode!=='text'?`<span class="stat">画像 ${images.length}枚</span>`:''}${mode!=='image'?`<span class="stat">テキスト抽出済み</span>`:''}</div>${mode!=='text'&&images.length===1?`<div class="preview-grid"><div class="preview-card"><img src="${URL.createObjectURL(images[0].blob)}"><div>${esc(images[0].name)}</div></div></div>`:''}${mode!=='image'?`<textarea class="text-output" readonly>${textParts.join('\n')}</textarea>`:''}<div class="extract-actions">${buttons}</div>`;if(mode!=='text'&&images.length===1)$('#download-image').onclick=()=>dl(images[0].blob,images[0].name);if(mode!=='text'&&images.length>1)$('#download-images').onclick=async()=>{const z=new JSZip();images.forEach(x=>z.file(x.name,x.blob));dl(await z.generateAsync({type:'blob'}),`${base(selected.name)}_画像.zip`)};if(mode!=='image')$('#download-text').onclick=()=>dl(new Blob([textParts.join('\n')],{type:'text/plain;charset=utf-8'}),`${base(selected.name)}_テキスト.txt`)}catch(e){console.error(e);showError(e.message==='password'?'パスワードで保護されたPDFには対応していません。':'PDFを読み込めませんでした。PDFが壊れていないか確認してください。')}};