import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
import { PDFDocument, rgb } from 'https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.esm.min.js';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s),pages=$('#pages'),file=$('#file'),save=$('#save'),color=$('#color'),size=$('#size');let pdf=null,src=null,tool='select';
function setTool(t){tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t))}document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
file.onchange=async()=>{src=file.files[0];if(!src)return;pages.innerHTML='';$('#empty').hidden=true;pages.hidden=false;save.disabled=false;pdf=await pdfjsLib.getDocument({data:await src.arrayBuffer()}).promise;for(let n=1;n<=pdf.numPages;n++)await renderPage(n)};
async function renderPage(n){const p=await pdf.getPage(n),v=p.getViewport({scale:Math.min(1.6,1100/p.view[2])}),w=document.createElement('div');w.className='pdf-page';w.innerHTML=`<div class="page-tools">${n} ページ</div><canvas></canvas><div class="overlay"></div>`;pages.appendChild(w);const c=w.querySelector('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const o=w.querySelector('.overlay');o.style.width=v.width+'px';o.style.height=v.height+'px';o.onpointerdown=e=>start(e,o);o.onpointermove=e=>move(e,o);o.onpointerup=end}
let down=false,x0=0,y0=0,item=null;const pos=(e,o)=>{const r=o.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
function start(e,o){if(tool==='select')return;e.preventDefault();const p=pos(e,o);x0=p.x;y0=p.y;o.setPointerCapture?.(e.pointerId);if(['text','stamp','signature'].includes(tool)){addItem(p.x,p.y,o);return}down=true;if(tool==='draw'){item=document.createElement('canvas');item.className='ink';item.width=o.clientWidth;item.height=o.clientHeight;o.appendChild(item);const c=item.getContext('2d');c.strokeStyle=color.value;c.lineWidth=+size.value;c.lineCap='round';c.beginPath();c.moveTo(x0,y0)}else{item=document.createElement('div');item.className='mark '+tool;item.style.cssText=`left:${x0}px;top:${y0}px;border-color:${color.value};background:${tool==='highlight'?'#ffe66d88':tool==='redact'?'#111':'transparent'}`;o.appendChild(item)}}
function move(e,o){if(!down||!item)return;const p=pos(e,o);if(tool==='draw'){const c=item.getContext('2d');c.lineTo(p.x,p.y);c.stroke()}else{item.style.left=Math.min(x0,p.x)+'px';item.style.top=Math.min(y0,p.y)+'px';item.style.width=Math.max(4,Math.abs(p.x-x0))+'px';item.style.height=Math.max(4,Math.abs(p.y-y0))+'px'}}function end(){down=false;item=null}
function addItem(t,x,y,o){const el=document.createElement('div');el.className='item '+t;el.style.left=x+'px';el.style.top=y+'px';if(t==='text'){const i=document.createElement('input');i.className='text-input';i.placeholder='文字を入力';el.appendChild(i);i.focus();i.onblur=()=>el.dataset.text=i.value;i.onkeydown=e=>{if(e.key==='Enter')i.blur()}}else if(t==='stamp'){el.textContent='確認';el.dataset.text='確認'}else{const i=document.createElement('textarea');i.className='signature-input';i.placeholder='署名を入力';el.appendChild(i);i.focus();i.oninput=()=>el.dataset.text=i.value}o.appendChild(el)}
$('#clear').onclick=()=>{const p=document.querySelector('.pdf-page:hover');if(p)p.querySelector('.overlay').innerHTML=''};
save.onclick=async()=>{save.disabled=true;save.textContent='PDFを作成中…';try{const doc=await PDFDocument.load(await src.arrayBuffer()),ps=doc.getPages();document.querySelectorAll('.pdf-page').forEach((w,i)=>{const p=ps[i],o=w.querySelector('.overlay'),sx=p.getWidth()/o.clientWidth,sy=p.getHeight()/o.clientHeight;o.querySelectorAll('.mark').forEach(e=>{const x=parseFloat(e.style.left)*sx,y=p.getHeight()-(parseFloat(e.style.top)+parseFloat(e.style.height))*sy,ww=parseFloat(e.style.width)*sx,hh=parseFloat(e.style.height)*sy;if(e.classList.contains('highlight'))p.drawRectangle({x,y,width:ww,height:hh,color:rgb(1,.9,.1),opacity:.35});else if(e.classList.contains('redact'))p.drawRectangle({x,y,width:ww,height:hh,color:rgb(.05,.05,.05)});else if(e.classList.contains('underline'))p.drawLine({start:{x,y},end:{x:x+ww,y},thickness:+size.value,color:rgb(.15,.3,.9)});else if(e.classList.contains('circle'))p.drawEllipse({x:x+ww/2,y:y+hh/2,xScale:ww/2,yScale:hh/2,borderWidth:+size.value,borderColor:rgb(.15,.3,.9)});else p.drawRectangle({x,y,width:ww,height:hh,borderWidth:+size.value,borderColor:rgb(.15,.3,.9)})});o.querySelectorAll('.item').forEach(e=>{const text=e.dataset.text;if(text)p.drawText(text,{x:parseFloat(e.style.left)*sx,y:p.getHeight()-(parseFloat(e.style.top)+24)*sy,size:16,color:rgb(.1,.12,.18)})})});const out=await doc.save(),u=URL.createObjectURL(new Blob([out],{type:'application/pdf'})),a=document.createElement('a');a.href=u;a.download=src.name.replace(/\.pdf$/i,'')+'_編集済み.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert('保存に失敗しました。')}finally{save.disabled=false;save.textContent='編集済みPDFを保存'}};
